### ISSUE TITLE
No matching version found for @serverless/platform-sdk@^0.2.0

### ISSUE THREAD

**Issue by jussikinnula** [serverless/platform-sdk#9]
The npm package `serverless` version 1.29.2 has a dependency for `@serverless/platform-sdk` version ^0.2.0, which does not exist.

```$ npm view @serverless/platform-sdk

@serverless/platform-sdk@0.1.5 | Apache-2.0 | deps: 14 | versions: 12
Serverless Platform SDK
https://github.com/serverless/platform-sdk#readme

...```

Also, when trying to install the package manually with specific version the installation fails:

```$ npm install --save @serverless/platform-sdk@^0.2.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @serverless/platform-sdk@^0.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.```

In https://www.npmjs.com/package/@serverless/platform-sdk it states that latest version should be 0.2.0. I'm just guessing that the publishing for 0.2.0 failed.

**Comment by alexdebrie** [comment]
Hey @jussikinnula, thanks for reporting. I'm able to install the 0.2.0 version of the `@serverless/platform-sdk` package, so I don't think it was a publishing issue to NPM.

I have seen trouble with scoped packages before, and I wonder if that's happening here. Could you answer a few questions for me:

1. What version of Node are you using?
2. What version of NPM are you using?
3. Are you behind some kind of proxy?
4. Do you use the public NPM registry (`https://registry.npms.org`) or are you running your own?

Also cc @miki79 as it seems like you're having the same issue. Can you answer the questions above ^^?

Thanks!

**Comment by miki79** [comment]
npm 6.2.0
node v8.11.3
no proxy
using the public NPM registry

This is the debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@8/8.11.3_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@serverless/platform-sdk' ]
2 info using npm@6.2.0
3 info using node@v8.11.3
4 verbose npm-session c08de9df047c5300
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@serverless%2fplatform-sdk 2455ms
```

but if I call `wget "https://registry.npmjs.org/@serverless%2fplatform-sdk"` it works, so I guess it's some problem with my npm

**Comment by alexdebrie** [comment]
@miki79 Looks like it might be related to this issue: https://github.com/npm/npm/issues/17966


Do you have an `_auth` key in your `.npmrc` file? If so, could you try commenting it out and then installing?

**Comment by miki79** [comment]
@alexdebrie yes, that was the problem. 
Thank you very much for your help

**Comment by alexdebrie** [comment]
You're welcome!

cc @jussikinnula to see if this will help you too

**Comment by sinkang** [comment]
after commneting out.. i'm getting unauthorized error instead

**Comment by alexdebrie** [comment]
Sorry to hear that, @sinkang. Can you paste the following information:

1. The stacktrace you get with the error.

2. The node version you're using -- `node --version`

3. The npm version you're using -- `npm --version`

Thanks!

**Comment by JamaalScott** [comment]
We are also getting the same error as of this week.  Or at least we just tried to deploy and ran into the error.

We do have private packages and need to reference them, but even removing the auth line and just trying installing serverless results in a 404.

$ npm install serverless
npm ERR! code E404
npm ERR! 404 Not Found: @serverless/platform-sdk@^0.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /<user_home>/.npm/_logs/2018-08-06T22_54_10_886Z-debug.log

$ npm --version
5.6.0
$ node --version
v8.11.1

Relevant part of the log:
123 verbose stack Error: 404 Not Found: @serverless/platform-sdk@^0.2.0
123 verbose stack     at fetch.then.res (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
123 verbose stack     at tryCatcher (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
123 verbose stack     at Promise._settlePromiseFromHandler (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
123 verbose stack     at Promise._settlePromise (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
123 verbose stack     at Promise._settlePromise0 (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
123 verbose stack     at Promise._settlePromises (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
123 verbose stack     at Async._drainQueue (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
123 verbose stack     at Async._drainQueues (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
123 verbose stack     at Immediate.Async.drainQueues (/<user_home>/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
123 verbose stack     at runCallback (timers.js:794:20)
123 verbose stack     at tryOnImmediate (timers.js:752:5)
123 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
124 verbose cwd /<user_home>/dev/hdr
125 verbose Darwin 17.7.0
126 verbose argv "/usr/local/bin/node" "/<user_home>/.nvm/versions/node/v10.0.0/bin/npm" "install" "serverless"
127 verbose node v8.11.1
128 verbose npm  v5.6.0
129 error code E404
130 error 404 Not Found: @serverless/platform-sdk@^0.2.0
131 verbose exit [ 1, true ]

**Comment by sinkang** [comment]
Hi @alexdebrie , information is below. Thanks.

sins-MacBook-Air:~ sinkang$ npm install -g serverless -dd
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'serverless',
npm verb cli   '-dd' ]
npm info using npm@6.3.0
npm info using node@v10.0.0
npm verb npm-session 151ef39c91eec46d
npm http fetch GET 401 https://repo.cloud.accedo.tv/artifactory/api/npm/public-npm-repos/serverless 1244ms
npm timing stage:rollbackFailedOptional Completed in 4ms
npm timing stage:runTopLevelLifecycles Completed in 2572ms
npm verb stack Error: 401 Unauthorized: serverless@latest
npm verb stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:696:18)
npm verb stack     at tryOnImmediate (timers.js:667:5)
npm verb stack     at processImmediate (timers.js:649:5)
npm verb cwd /Users/sinkang
npm verb Darwin 17.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "serverless" "-dd"
npm verb node v10.0.0
npm verb npm  v6.3.0
npm ERR! code E401
npm ERR! 401 Unauthorized: serverless@latest
npm verb exit [ 1, true ]
npm timing npm Completed in 4808ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinkang/.npm/_logs/2018-08-07T02_38_21_659Z-debug.log
sins-MacBook-Air:~ sinkang$

**Comment by sinkang** [comment]
hi @alexdebrie , It was my bad... I was using private registry... after I've changed to NPM public registry. it is working fine. Thanks.
